import type { Metadata } from 'next';
import '../globals.css';
import NavBar from '../components/common/navBar';
import Footer from '../components/common/footer';
import Script from 'next/script';




export const metadata: Metadata = {
  title: 'Pet24',
  description: 'Generated by Pet24',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <NavBar></NavBar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
