
import type { Metadata } from 'next';
import '../globals.css';
import NavBar from '../components/common/navBar';
import Footer from '../components/common/footer';
import classes from './layout.module.css'
import DashBoardNavBar from '../components/common/dashBoardNavBar';


export const metadata: Metadata = {
  title: 'Pet24',
  description: 'Generated by Pet24',
}

export default function DashBoardLayout() {
  return (
    <>  
        <html>
            <body>
                <NavBar></NavBar>

                <div className={classes.dashboardWrapper}>
                    <DashBoardNavBar></DashBoardNavBar>
                </div>
            </body>
        </html>

    </>
  )
};






{/* <div className={classes.dashboardWrapper}>
<DashBoardNavBar></DashBoardNavBar>

<div className={classes.dashboardContentWrapper}>
    {children}
</div>
</div> */}