
import type { Metadata } from 'next';
import '../globals.css';
import NavBar from '../components/common/navBar';
import Footer from '../components/common/footer';
import classes from './layout.module.css'
import DashBoardNavBar from '../components/dashBoard/dashBoardNavBar';


export const metadata: Metadata = {
  title: 'Pet24',
  description: 'Generated by Pet24',
}

export default function DashBoardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>  
        <html>
            <body>
                <NavBar></NavBar>
                <div className={classes.dashboardWrapper}>
                  <div>
                    <DashBoardNavBar></DashBoardNavBar>
                  </div>
                  <div className={classes.dashboardContentWrapper}>
                      {children}
                  </div>
                </div> 
            </body>
        </html>

    </>
  )
};






{/* <div className={classes.dashboardWrapper}>
<DashBoardNavBar></DashBoardNavBar>

<div className={classes.dashboardContentWrapper}>
    {children}
</div>
</div> */}