import type { Metadata } from 'next';
import '../globals.css';
import NavBar from '../components/navBar';
import Footer from '../components/footer';
import Script from 'next/script';




export const metadata: Metadata = {
  title: 'Pet24',
  description: 'Generated by Pet24',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script 
        defer
        type="text/javascript" 
        strategy="beforeInteractive" 
        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=00686a05b852e4dd7e1d395281714282&libraries=services&autoload=false"/>
      <body >
        <NavBar></NavBar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
